Скопируем и обработаем таблицу по безработным с сайта https://gogov.ru/articles/unemployment-rate так как не было возможности скачать её.

In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np
import re

In [ ]:
#   Изменение любого копипаста в строку
s = input()
l = s.split()
s1 = ','.join(l)
print(s1)

In [2]:
Stroka = 'Адыгея,16.8,17.0,16.4,17.3,17.6,18.2,17.7,17.3,16.6,16.5,17.2,19.1,15.2,14.7,21.4,28.0,26.2,32.9,29.1,27,27.9,28.9,Алтай,11.6,13.8,10.5,10.8,11.8,11.9,9.7,10.2,11.5,11.5,12.8,12.3,13.7,12.3,8.8,10.9,8.9,9.3,9.3,10.4,8.8,16,Алтайский,край,60.6,65.2,66.1,70.3,78.2,99.6,94.8,83.4,95.8,74.4,103.2,110.6,152.0,105.1,81.7,114.4,112.9,117.6,155.3,106.1,123.7,149,Амурская,обл.,20.7,24.0,21.9,22.8,24.3,24.6,24.0,23.5,25.7,22.7,27.0,29.6,36.7,23.2,26.1,35.3,41.4,49.8,45.0,48.4,54.5,66.1,Архангельская,обл.,35.0,38.3,33.2,35.1,36.2,40.2,40.0,43.1,36.6,32.6,36.7,44.1,45.9,43.7,35.2,39.4,35.4,47.0,68.3,56.4,59.5,87.4,Астраханская,обл.,39.0,39.6,38.7,38.6,40.0,40.0,39.7,39.7,39.9,41.0,46.8,43.1,52.4,39.4,45.2,42.4,60.5,60.2,51.8,52.3,52.6,57.9,Башкортостан,83.2,111.7,83.8,96.0,111.5,116.0,123.3,104.9,116.0,123.8,158.7,181.9,190.3,105.1,132.0,129.5,142.6,140.2,163.8,161.1,204.5,227.9,Белгородская,обл.,34.7,40.6,31.9,32.6,32.1,32.5,32.8,32.5,32.2,29.5,33.2,40.6,37.4,29.6,31.4,42.7,42.0,45.9,59.8,58.5,48.2,44.9,Брянская,обл.,20.1,23.3,22.5,24.0,27.0,28.7,29.0,31.9,33.3,32.7,45.5,51.9,68.2,42.2,42.5,44.8,43.9,58.4,47.7,54.4,63.8,88.8,Бурятия,41.3,45.0,39.9,42.2,42.4,43.5,42.4,38.5,37.0,36.5,41.6,49.3,63.3,58.6,60.5,64.2,54.9,67.9,80.8,69.7,81.3,92.9,Владимирская,обл.,27.5,39.6,29.2,33.8,35.3,41.0,42.3,32.9,29.2,34.1,44.3,46.6,66.5,44.9,53.7,86.3,72.9,73.3,81.1,83.7,80.4,95.5,Волгоградская,обл.,61.6,94.4,66.2,71.9,76.8,88.0,94.7,86.6,89.1,80.4,91.9,105.4,137.7,107.8,86.1,116.5,88.1,125.8,144.2,114.1,125,126.5,Вологодская,обл.,25.9,35.0,25.4,29.3,30.9,40.2,41.7,34.8,38.2,37.0,47.1,51.2,52.0,36.8,26.4,35.9,34.1,40.4,31.0,39.5,58.7,55.4,Воронежская,обл.,45.3,50.4,42.0,43.3,51.2,52.3,52.0,52.7,54.1,64.6,75.6,86.8,100.8,60.8,59.4,63.7,87.6,95.7,91.5,101.3,105.7,118.6,Дагестан,206.4,201.5,179.3,160.0,163.5,146.2,140.3,135.2,152.8,155.3,172.2,188.5,171.4,174.8,252.6,270.1,264.1,299.6,213.4,260,280.7,255.1,Еврейская,АО,4.3,4.9,4.8,5.6,6.9,6.9,6.7,7.5,7.3,7.4,7.6,8.2,7.4,8.4,7.9,8.5,7.2,7.3,6.3,8.6,8.6,13.9,Забайкальский,край,48.8,51.5,48.7,54.5,57.4,57.6,55.7,53.7,56.0,56.3,56.9,58.9,65.6,81.5,46.6,33.2,48.9,65.6,72.8,62.7,81.9,76.7,Ивановская,обл.,23.7,27.9,19.5,22.1,25.4,29.9,30.9,22.9,28.7,35.0,36.7,42.2,58.8,29.5,24.1,23.5,39.5,26.9,36.5,39.1,33.9,61.4,Ингушетия,82.3,77.7,68.2,66.4,67.6,69.8,68.2,63.2,87.7,96.3,91.9,89.0,95.3,78.5,65.9,63.7,110.6,57.5,68.0,66.5,51.4,30.8,Иркутская,обл.,68.8,89.0,77.0,89.3,105.3,110.2,103.1,109.7,104.4,97.8,114.9,127.3,137.9,109.9,104.9,108.3,127.5,136.8,145.0,141.5,144.9,156.4,Кабардино-Балкария,52.8,66.9,47.7,47.0,45.3,44.5,43.2,41.2,44.2,34.1,38.8,48.2,56.4,67.7,72.5,88.8,91.1,95.1,90.7,71.7,63.1,68.1,Калининградская,обл.,27.1,31.3,23.8,24.8,26.9,31.5,30.5,28.8,29.7,38.8,47.8,52.4,55.6,45.7,17.8,22.2,33.4,33.0,37.9,35.1,39.1,77.4,Калмыкия,12.1,12.9,12.2,13.4,13.9,15.3,15.4,16.0,17.7,19.1,21.2,22.0,25.1,24.1,21.7,25.1,26.7,30.9,24.0,25,26.5,29.8,Калужская,обл.,21.6,25.4,19.8,21.4,21.6,22.7,22.9,22.4,24.8,23.6,31.2,37.6,35.0,25.9,27.4,30.5,31.1,34.7,32.7,34.6,33.1,49.3,Камчатский,край,6.3,6.9,6.8,8.8,7.7,7.6,8.4,11.5,10.8,10.9,11.7,13.3,14.4,16.8,17.9,15.9,17.3,21.3,26.2,24,31.5,34.6,Карачаево-Черкесия,26.2,30.1,23.8,25.9,28.4,30.9,32.8,29.6,22.2,21.1,22.9,23.9,28.5,34.4,41.4,40.8,29.3,32.9,34.7,23.7,35.7,40.6,Карелия,19.5,26.0,22.6,27.0,27.4,30.2,28.7,26.4,27.0,23.1,28.4,32.5,34.0,29.6,21.5,12.4,32.6,27.8,30.8,29.6,32.5,43,Кемеровская,обл.,68.5,85.4,70.8,80.9,95.1,107.7,105.5,88.0,85.3,98.9,113.9,125.9,138.6,95.2,89.6,107.2,127.0,143.9,144.4,135.2,141.7,156.7,Кировская,обл.,30.9,34.1,30.4,34.2,35.6,36.5,36.2,34.4,38.3,48.8,58.8,63.5,81.0,54.7,43.8,61.3,57.1,68.7,58.1,55.9,63.9,67.7,Коми,28.5,32.1,29.1,32.0,34.8,40.4,33.2,28.7,35.3,31.5,41.0,52.1,58.8,39.0,54.0,64.6,59.6,65.6,66.7,49.3,75.8,65.9,Костромская,обл.,13.5,17.1,12.6,14.3,17.3,18.1,17.3,14.5,17.1,16.8,18.1,21.4,29.7,18.1,12.2,18.2,18.0,21.8,22.0,18.5,22.2,33.3,Краснодарский,край,142.2,160.0,135.7,145.4,158.4,159.5,162.5,148.8,160.0,146.8,153.2,173.1,190.5,125.2,168.3,177.6,178.6,209.8,237.7,185.7,257.2,308.5,Красноярский,край,52.0,87.9,66.6,73.3,85.4,90.2,93.3,76.3,86.1,84.0,90.4,97.1,145.5,95.8,118.1,138.2,152.0,127.9,147.4,119.8,148.2,189.8,Крым,53.4,58.5,51.4,53.8,58.4,61.7,69.2,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,Курганская,обл.,27.9,30.4,28.4,30.6,36.7,34.5,31.8,29.9,33.2,37.7,44.4,55.3,58.1,42.4,36.9,57.3,55.2,60.6,46.3,51.2,62.4,67.3,Курская,обл.,22.7,27.1,22.5,23.0,23.5,24.4,24.0,22.5,26.6,28.9,36.1,47.6,51.0,37.3,29.1,42.5,43.7,44.4,49.5,43.8,64.1,66.5,Ленинградская,обл.,36.9,51.9,37.6,39.8,45.1,44.3,48.8,43.2,40.9,31.7,42.2,49.9,66.6,57.9,37.2,54.1,65.9,62.2,74.9,58.9,61.9,82.4,Липецкая,обл.,25.3,25.8,22.3,23.0,23.1,23.6,24.1,22.0,22.4,22.6,29.9,27.8,34.9,30.7,16.7,30.0,48.3,25.6,27.0,29.7,38.4,52.1,Магаданская,обл.,4.3,4.9,3.9,4.4,4.8,4.0,4.0,2.9,2.8,3.4,4.5,5.7,6.7,7.4,5.8,5.3,7.0,8.7,10.8,9.1,12.7,12.9,Марий,Эл,17.7,22.1,15.4,16.6,21.3,21.3,19.0,17.3,19.2,23.8,37.6,39.4,42.1,34.1,34.6,36.3,38.2,35.9,41.8,50.6,34.1,43.7,Мордовия,17.8,21.6,18.5,17.7,18.6,18.8,18.9,19.0,20.2,22.4,24.2,25.0,24.5,12.9,16.0,20.4,28.7,26.2,33.1,40.3,44,47.1,Москва,193.5,193.0,99.5,90.1,99.6,127.1,125.2,104.4,117.1,54.8,95.4,114.8,176.3,59.2,52.0,99.5,49.5,96.3,74.1,81.4,116.5,205.3,Московская,обл.,140.5,150.3,114.1,110.6,131.1,133.2,129.3,104.9,108.0,116.3,148.4,130.5,187.4,105.7,78.8,110.8,117.9,139.9,159.8,152.5,196.9,283.5,Мурманская,обл.,24.2,31.8,22.9,29.0,30.9,34.3,35.3,30.7,33.7,36.3,40.6,41.8,37.1,32.7,30.1,33.4,44.2,54.3,52.4,54.5,69.2,72.7,Ненецкий,АО,1.6,1.9,1.8,1.8,1.8,2.0,1.8,1.2,1.6,1.6,2.0,1.5,2.3,1.9,1.5,1.3,2.5,1.7,2.0,1.5,1.5,2.4,Нижегородская,обл.,73.1,80.0,71.4,73.1,75.2,76.3,75.2,75.2,75.8,98.1,128.7,137.7,135.1,101.3,82.3,96.5,107.2,133.3,112.3,141.5,149.2,144.4,Новгородская,обл.,12.2,16.7,11.0,13.0,14.9,15.6,14.8,12.0,15.6,13.8,16.5,19.2,21.0,16.7,18.1,18.7,20.3,21.2,17.6,21.5,23.1,27.5,Новосибирская,обл.,87.4,92.8,86.9,96.2,85.3,107.6,98.9,73.6,84.2,80.7,98.9,109.5,141.0,105.0,97.2,101.1,108.0,121.4,150.1,154.1,162,183.5,Омская,обл.,65.4,90.8,65.5,69.3,72.3,75.7,71.7,70.1,72.4,72.0,83.8,85.5,88.6,82.5,82.6,92.4,90.1,89.1,95.9,95.4,97.5,145.4,Оренбургская,обл.,44.4,55.4,41.2,44.7,45.7,50.0,48.9,46.4,52.6,56.0,66.0,77.0,92.6,69.5,75.4,68.5,96.4,118.1,117.4,105.1,86,127.1,Орловская,обл.,16.4,21.3,18.5,18.2,24.6,24.7,23.9,20.0,23.0,20.9,24.4,35.5,39.3,24.1,22.9,25.3,26.3,26.6,34.1,29.7,33.8,37.6,Пензенская,обл.,28.1,32.3,28.3,30.4,30.5,32.7,32.8,32.6,33.6,34.5,37.2,44.1,56.0,53.8,35.7,45.9,46.8,46.7,63.9,51.3,100.2,86.4,Пермский,край,57.0,70.5,63.1,67.8,77.5,76.5,81.7,74.8,86.6,84.9,104.1,116.7,140.6,117.6,91.8,98.8,112.5,104.6,103.3,130.8,98.2,151.7,Приморский,край,42.2,54.7,51.6,55.9,56.3,62.8,73.4,72.9,75.8,72.9,85.0,101.7,103.8,81.6,75.7,82.4,85.7,105.0,90.1,97.2,95.8,139.6,Псковская,обл.,14.9,19.6,16.1,18.2,20.8,22.3,23.2,22.3,24.4,23.2,33.1,33.8,39.5,23.8,17.7,26.7,23.5,20.1,29.8,27.8,37.3,43.1,Ростовская,обл.,85.9,106.4,101.2,109.2,120.4,125.9,130.3,125.8,128.7,130.1,159.5,167.1,184.1,142.6,147.2,173.2,181.6,191.8,263.4,239.8,271.8,318.6,Рязанская,обл.,20.6,27.6,21.1,22.0,22.0,23.8,25.1,23.9,26.1,25.8,41.2,48.3,51.8,31.0,22.4,28.2,32.0,34.0,49.2,50.2,63.8,57.7,Самарская,обл.,58.4,74.6,65.6,63.8,72.2,71.9,60.1,53.1,55.7,60.0,88.5,101.2,107.5,75.4,75.0,74.8,93.2,93.5,73.6,93.7,104.2,173.9,Санкт-Петербург,63.1,90.0,42.2,44.7,50.3,49.8,61.9,39.0,43.5,33.0,55.8,74.3,116.6,57.4,57.7,64.4,57.4,70.1,105.0,86.3,98.3,153.1,Саратовская,обл.,52.4,65.0,51.9,60.3,57.4,63.7,59.0,58.4,65.7,69.0,78.2,85.8,115.3,100.2,105.2,107.8,121.3,128.1,134.9,98.4,126.3,129.8,Саха,34.4,37.0,34.4,34.7,35.6,35.0,36.7,37.3,37.4,40.0,44.1,43.7,44.1,45.6,38.1,47.4,44.9,44.5,47.1,35.1,39,54.5,Сахалинская,обл.,14.4,15.3,14.3,14.8,16.5,17.6,17.8,18.4,20.5,21.9,22.9,25.6,28.6,22.1,13.4,14.6,23.6,21.8,27.5,27.2,36.4,39.8,Свердловская,обл.,86.2,122.2,89.4,103.0,119.2,137.7,149.4,138.4,136.3,133.4,167.2,193.9,191.2,112.8,125.2,167.4,158.7,171.0,178.3,195.2,179.5,233.4,Севастополь,9.6,10.0,8.6,9.3,9.2,12.0,16.6,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,Северная,Осетия,42.1,44.0,37.5,36.5,39.4,31.9,30.7,29.2,27.8,27.8,29.5,36.8,38.5,35.3,31.1,25.9,29.0,37.1,34.1,43.9,59.5,96,Смоленская,обл.,24.2,25.3,25.3,26.2,29.8,31.4,32.8,26.9,28.1,30.9,41.5,40.8,43.6,37.2,36.9,43.6,41.4,48.1,56.4,59.5,53.5,67.2,Ставропольский,край,72.2,84.6,66.9,69.0,70.2,78.3,77.8,73.0,76.9,74.3,82.4,94.1,116.8,108.3,88.8,114.8,89.3,119.9,133.6,115.8,120.4,177.7,Тамбовская,обл.,19.8,22.8,19.6,20.5,22.5,23.6,24.3,22.8,24.6,26.1,35.9,43.4,50.4,52.0,50.4,49.1,48.2,49.6,50.0,52.6,63.4,47.6,Татарстан,53.6,73.7,66.4,67.7,70.8,77.5,82.0,80.8,80.7,84.6,94.9,126.3,168.1,96.0,108.1,105.5,125.4,138.4,124.7,99.7,116.1,158.7,Тверская,обл.,25.3,29.0,26.7,27.9,31.2,39.9,39.1,38.0,38.3,36.5,43.3,47.1,57.6,36.4,30.4,32.8,42.4,38.6,47.1,34.6,55.3,68.5,Томская,обл.,37.0,46.4,29.5,34.5,33.8,39.7,40.4,41.8,39.2,41.6,46.4,41.8,46.7,43.0,37.0,47.3,54.8,54.4,69.3,59.1,51.2,68,Тульская,обл.,30.1,35.1,29.9,30.6,30.7,33.0,33.2,33.5,33.9,37.4,42.5,47.0,48.6,27.2,21.6,22.7,40.3,38.7,42.6,49.4,43.8,83.4,Тыва,19.1,23.5,14.4,18.8,23.1,21.3,23.2,23.8,23.5,22.0,23.3,27.6,27.0,22.6,21.9,26.0,29.3,25.8,27.8,26,28.9,27.2,Тюменская,обл.,32.0,35.3,29.6,32.3,36.2,40.2,43.2,38.3,36.4,39.5,43.0,47.8,51.9,39.2,34.4,55.2,32.5,56.9,53.8,50.9,71,69.7,Удмуртия,34.2,48.2,32.6,37.8,38.1,42.3,40.9,41.7,46.8,49.8,58.0,77.5,74.9,65.2,67.8,70.9,63.9,64.2,53.3,65,59.4,78.3,Ульяновская,обл.,26.2,29.2,23.0,23.4,28.3,29.7,32.0,31.0,37.4,37.9,47.3,58.8,60.2,48.5,31.2,46.0,53.5,64.2,48.1,42.9,57,44.7,Хабаровский,край,21.8,28.7,26.8,27.3,35.7,36.6,38.9,43.9,42.2,47.6,49.7,65.9,75.8,65.3,41.0,44.1,43.1,49.8,46.9,51.9,77.5,93.5,Хакасия,16.2,20.9,14.9,13.2,12.7,16.3,15.3,16.1,15.8,20.8,19.4,24.3,23.6,18.9,17.6,23.7,24.6,27.2,28.4,21,22.8,31.8,Ханты-Мансийский,АО,23.9,27.2,22.4,22.7,30.0,41.7,40.5,42.1,43.7,49.9,56.9,68.6,62.3,70.0,66.9,52.8,67.2,79.2,77.8,80.5,88.8,87.7,Челябинская,обл.,91.5,125.9,95.1,105.3,123.5,130.5,129.4,116.1,113.3,120.2,124.3,139.9,148.9,79.1,43.9,93.2,95.1,89.5,106.5,110.1,149.9,155.6,Чечня,94.9,120.8,85.9,86.3,87.1,98.1,105.8,135.9,174.7,177.9,205.3,238.3,194.4,172.1,254.8,311.2,-,-,-,-,-,-,Чувашия,29.0,36.6,28.3,31.2,31.9,33.9,33.2,34.0,38.3,38.4,51.8,63.4,78.0,53.9,60.5,58.1,77.4,64.0,54.8,63.1,62.5,61.3,Чукотский,АО,0.8,1.4,1.2,0.9,0.9,1.1,1.3,1.1,1.1,1.4,1.8,1.5,1.6,1.7,1.2,1.3,1.4,1.2,1.6,1.6,2.4,3.7,Ямало-Ненецкий,АО,6.6,7.3,6.1,6.6,10.0,8.4,11.3,10.3,10.3,11.4,11.3,13.4,14.3,19.4,8.6,16.9,22.3,19.4,16.9,20.8,21.3,25.8,Ярославская,обл.,39.0,47.4,35.0,36.4,44.1,45.2,36.8,26.4,30.2,22.7,34.5,50.9,55.4,41.1,23.6,20.5,27.2,32.3,41.0,26.8,48.6,55.3,Россия,3,630.5,4,321.3,3,464.8,3,658.5,3,969.5,4,243.5,4,263.9,3,889.4,4,137.4,4,130.7,4,922.4,5,544.2,6,283.7,4,697.0,4,518.6,5,250.2,5,242.0,5,666.0,5,933.5,5,698.3,6,423.7,7,699.5'

Создадим функцию для изменения наименования в строке и преобразование в список

In [3]:
def replace_Tur(Characters):
    Characters = Characters.replace(",обл."," обл.")
    Characters = Characters.replace(",АО"," АО")
    Characters = Characters.replace(",край"," край")
    Characters = Characters.replace(",Эл"," Эл")
    Characters = Characters.replace(",Осетия"," Осетия")
    Characters = Characters.split(',')
    Characters = list(filter(None, Characters))
    return Characters

In [4]:
Spisok = replace_Tur(Stroka)
my_list = Spisok[:-45]
print(len(my_list))

1955

Сделаем из списка датафрейм

In [5]:
df = pd.DataFrame(np.array(my_list).reshape(85, 23)).add_prefix("col")
# заменим '-' на Nan
mask = df.applymap(lambda x: x == '-')
df = df.replace('-', np.nan).fillna(method='ffill')
# переведём в тип float
df1 = df['col0']
df.drop(['col0'], axis=1, inplace = True)
for col in df.columns:
    df[col] = df[col].astype(float)
# умножим на 1000, так как в таблице приведены данные в тыс. чел
df = df *1000
df = pd.concat([df1, df], axis=1)
df.head(3)

,col0,col1,col2,col3,col4,col5,col6,col7,col8,col9,...,col13,col14,col15,col16,col17,col18,col19,col20,col21,col22
0,Адыгея,16800.0,17000.0,16400.0,17300.0,17600.0,18200.0,17700.0,17300.0,16600.0,...,15200.0,14700.0,21400.0,28000.0,26200.0,32900.0,29100.0,27000.0,27900.0,28900.0
1,Алтай,11600.0,13800.0,10500.0,10800.0,11800.0,11900.0,9700.0,10200.0,11500.0,...,13700.0,12300.0,8800.0,10900.0,8900.0,9300.0,9300.0,10400.0,8800.0,16000.0
2,Алтайский край,60600.0,65200.0,66100.0,70300.0,78200.0,99600.0,94800.0,83400.0,95800.0,...,152000.0,105100.0,81700.0,114400.0,112900.0,117600.0,155300.0,106100.0,123700.0,149000.0

Укажим наименования столбцов и отсортируем года в обратном порядке

In [6]:
df.rename(columns={df.columns[i]: f'year{i-2022}' for i in range(len(df.columns))}, inplace=True)
df.rename(columns=lambda x: x.replace('year-', ''), inplace=True)
# отсортируем столбцы
df = df.reindex(sorted(df.columns), axis=1)
# переставим столбец регион в начало
df['2000'] = df['2022']
df.rename(columns={'2000': 'регион'}, inplace=True)
df.drop(['2022'], axis=1, inplace = True)
df.head(3)

,регион,2001,2002,2003,2004,2005,2006,2007,2008,2009,...,2012,2013,2014,2015,2016,2017,2018,2019,2020,2021
0,Адыгея,27900.0,27000.0,29100.0,32900.0,26200.0,28000.0,21400.0,14700.0,15200.0,...,16500.0,16600.0,17300.0,17700.0,18200.0,17600.0,17300.0,16400.0,17000.0,16800.0
1,Алтай,8800.0,10400.0,9300.0,9300.0,8900.0,10900.0,8800.0,12300.0,13700.0,...,11500.0,11500.0,10200.0,9700.0,11900.0,11800.0,10800.0,10500.0,13800.0,11600.0
2,Алтайский край,123700.0,106100.0,155300.0,117600.0,112900.0,114400.0,81700.0,105100.0,152000.0,...,74400.0,95800.0,83400.0,94800.0,99600.0,78200.0,70300.0,66100.0,65200.0,60600.0

In [7]:
df.to_csv("social_russia_data/ezrabotnye.csv", index=False)

In [8]:
df1 = pd.read_csv('social_russia_data\ezrabotnye.csv')
df1.head(3)

,регион,2001,2002,2003,2004,2005,2006,2007,2008,2009,...,2012,2013,2014,2015,2016,2017,2018,2019,2020,2021
0,Адыгея,27900.0,27000.0,29100.0,32900.0,26200.0,28000.0,21400.0,14700.0,15200.0,...,16500.0,16600.0,17300.0,17700.0,18200.0,17600.0,17300.0,16400.0,17000.0,16800.0
1,Алтай,8800.0,10400.0,9300.0,9300.0,8900.0,10900.0,8800.0,12300.0,13700.0,...,11500.0,11500.0,10200.0,9700.0,11900.0,11800.0,10800.0,10500.0,13800.0,11600.0
2,Алтайский край,123700.0,106100.0,155300.0,117600.0,112900.0,114400.0,81700.0,105100.0,152000.0,...,74400.0,95800.0,83400.0,94800.0,99600.0,78200.0,70300.0,66100.0,65200.0,60600.0